
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: flashcards-development

test:
  <<: *default
  database: flashcards-test

production:
  <<: *default
  database: flashcards-production
